// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNFLpidGY7pk8pYPq3H7TsISFKZ3_7Uo',
    appId: '1:1048958527114:web:10bdfd03bfc02a98bbaf73',
    messagingSenderId: '1048958527114',
    projectId: 'fluttertest-69c66',
    authDomain: 'fluttertest-69c66.firebaseapp.com',
    databaseURL: 'https://fluttertest-69c66-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-69c66.firebasestorage.app',
    measurementId: 'G-P99QTGWZ48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxbxdxRXsV89YNtlB2eWvrYAgQmzYISmw',
    appId: '1:1048958527114:android:478262f3b5895a73bbaf73',
    messagingSenderId: '1048958527114',
    projectId: 'fluttertest-69c66',
    databaseURL: 'https://fluttertest-69c66-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-69c66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBmRTHwWg2Frf_2a6vJ7nNn8Pj11QGTQs',
    appId: '1:1048958527114:ios:f70b2616b1defcfebbaf73',
    messagingSenderId: '1048958527114',
    projectId: 'fluttertest-69c66',
    databaseURL: 'https://fluttertest-69c66-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-69c66.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBmRTHwWg2Frf_2a6vJ7nNn8Pj11QGTQs',
    appId: '1:1048958527114:ios:f70b2616b1defcfebbaf73',
    messagingSenderId: '1048958527114',
    projectId: 'fluttertest-69c66',
    databaseURL: 'https://fluttertest-69c66-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-69c66.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXNFLpidGY7pk8pYPq3H7TsISFKZ3_7Uo',
    appId: '1:1048958527114:web:d0c767bcb7f6935cbbaf73',
    messagingSenderId: '1048958527114',
    projectId: 'fluttertest-69c66',
    authDomain: 'fluttertest-69c66.firebaseapp.com',
    databaseURL: 'https://fluttertest-69c66-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-69c66.firebasestorage.app',
    measurementId: 'G-6EC5CF7JR3',
  );
}
